import{a as L,i as f,S as v}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const E="44822102-6d1d7649cda1a595bd957c97f",P="https://pixabay.com/api/";async function p(t,r,n){const i={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:n};return(await L.get(P,{params:i})).data}function y(t){f.error({title:"Error",message:t,position:"topRight"})}function h(t){f.info({title:"Info",message:t,position:"topRight"})}function g(t,r=!0){const n=document.querySelector(".gallery");r&&(n.innerHTML="");const i=t.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item">
            <div class="image-card">
                <img src="${e.webformatURL}" alt="${e.tags}">
                <div class="info">
                    <p>Likes ${e.likes}</p>
                    <p>Views ${e.views}</p>
                    <p>Comments ${e.comments}</p>
                    <p>Downloads ${e.downloads}</p>
                </div>
            </div>
        </a>
    `).join("");n.insertAdjacentHTML("beforeend",i)}const l=document.getElementById("loading"),I=document.querySelector(".gallery"),s=document.getElementById("load-more"),m=document.querySelector(".search-form");let a="",c=1;const d=15,b=new v(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",S);async function S(t){if(t.preventDefault(),a=t.currentTarget.elements.query.value,!a){y("Please enter something!");return}c=1,l.style.display="block",s.style.display="none";try{const r=await p(a,c,d);r.hits.length===0?h("Sorry, there are no images matching your search query. Please try again!"):(g(r.hits,!0),b.refresh(),r.hits.length===d&&setTimeout(()=>{s.style.display="block"},300))}catch{y("An error occurred while fetching images. Please try again later.")}finally{l.style.display="none",m.reset()}}s.addEventListener("click",w);async function w(){c+=1,s.style.display="none",l.style.display="block";try{const t=await p(a,c,d);g(t.hits,!1),b.refresh(),setTimeout(()=>{s.style.display="block"},300);const{height:r}=I.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),t.hits.length<d&&(h("We're sorry, but you've reached the end of search results."),setTimeout(()=>{s.style.display="none"},300),s.removeEventListener("click",w))}catch{y("An error occurred while fetching images. Please try again later.")}finally{l.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
